'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.commandCenter': 'Command Center',
    'nav.jobs': 'Jobs',
    'nav.cvVault': 'CV Vault',
    'nav.aiRecruiter': 'AI Recruiter',
    'nav.history': 'History',
    'nav.methodology': 'Methodology',
    'nav.about': 'About',
    'nav.ollamaLive': 'OLLAMA LIVE',
    'nav.smartHire': 'Smart Hire',
    
    // Landing Page
    'landing.badge': 'Smart Hire',
    'landing.heroTitle1': 'The Future of',
    'landing.heroTitle2': 'Smart Hiring',
    'landing.heroSubtitle': 'Transform your recruitment process with AI-powered CV analysis, intelligent candidate ranking, and real-time insights',
    'landing.getStarted': 'Get Started',
    'landing.learnMore': 'Learn More',
    'landing.howItWorks': 'How It Works',
    'landing.howItWorksSubtitle': 'Three simple steps to revolutionize your recruitment process',
    'landing.step1Title': 'Upload CVs',
    'landing.step1Desc': 'Upload candidate resumes or select from your database. Our AI instantly processes and extracts key information.',
    'landing.step2Title': 'AI Analysis',
    'landing.step2Desc': 'Advanced algorithms analyze skills, experience, projects, and education to create comprehensive candidate profiles.',
    'landing.step3Title': 'Get Rankings',
    'landing.step3Desc': 'Receive intelligent rankings with detailed explanations and insights to make informed hiring decisions.',
    'landing.powerfulFeatures': 'Powerful Features',
    'landing.featuresSubtitle': 'Everything you need for intelligent recruitment',
    'landing.feature1': 'Smart Parsing',
    'landing.feature1Desc': 'Extract key data from any CV format',
    'landing.feature2': 'Precision Matching',
    'landing.feature2Desc': 'Match candidates to job requirements',
    'landing.feature3': 'Skill Assessment',
    'landing.feature3Desc': 'Evaluate technical and soft skills',
    'landing.feature4': 'Team Collaboration',
    'landing.feature4Desc': 'Share insights with your team',
    'landing.feature5': 'Secure & Private',
    'landing.feature5Desc': 'Enterprise-grade data protection',
    'landing.feature6': 'Lightning Fast',
    'landing.feature6Desc': 'Process thousands of CVs instantly',
    'landing.ctaTitle': 'Ready to Transform Your Hiring?',
    'landing.ctaSubtitle': 'Join thousands of recruiters who have already revolutionized their hiring process',
    'landing.startNow': 'Start Now',
    'landing.footer': 'Capgemini Smart Hire. Powered by AI.',
    
    // Command Center
    'cc.title': 'Command Center',
    'cc.subtitle': 'AI-powered CV ranking and candidate analysis',
    'cc.targetRole': 'Target Role',
    'cc.targetRolePlaceholder': 'e.g., Full Stack Developer',
    'cc.requiredSkills': 'Required Skills',
    'cc.requiredSkillsPlaceholder': 'e.g., React, Node.js, Python',
    'cc.uploadCVs': 'Upload CVs',
    'cc.dragDrop': 'Drag & drop files here or click to browse',
    'cc.supportedFormats': 'Supports PDF, DOC, DOCX',
    'cc.loadFromDB': 'Load from Database',
    'cc.candidates': 'Candidates',
    'cc.noCandidates': 'No candidates loaded yet',
    'cc.rankCandidates': 'Rank Candidates',
    'cc.ranking': 'Ranking',
    'cc.results': 'Results',
    'cc.noResults': 'No ranking results yet',
    'cc.parsing': 'Parsing',
    'cc.checkWithAI': 'Check with AI',
    'cc.saveRanking': 'Save Ranking',
    'cc.subtitleDesc': 'Manage scanning, ranking, and analysis operations.',
    'cc.scanningDocuments': 'SCANNING DOCUMENTS',
    'cc.calculatingRankings': 'CALCULATING RANKINGS',
    'cc.uploadResumes': 'Upload Resumes',
    'cc.scanningDocumentsText': 'Scanning Documents',
    'cc.pleaseWait': 'Please wait while we process your files',
    'cc.dragDropFiles': 'Drag & drop PDF, DOCX or JSON files',
    'cc.processing': 'Processing...',
    'cc.selectFiles': 'Select Files',
    'cc.loadFromDatabase': 'Load from Database',
    'cc.selectCVsFromDB': 'Select CVs from your database',
    'cc.candidatesCount': 'Candidates',
    'cc.calculateRanking': 'Calculate Ranking',
    'cc.calculating': 'Calculating',
    'cc.roles': 'roles',
    'cc.languages': 'languages',
    'cc.saveToDatabase': 'Save to database',
    'cc.removeCandidate': 'Remove candidate',
    'cc.rankingResults': 'Ranking Results',
    'cc.readyToRank': 'Ready to Rank',
    'cc.readyToRankDesc': 'Upload candidate CVs and define job requirements to generate AI-powered rankings.',
    'cc.uploadCVsFirst': 'Upload CVs first',
    'cc.failedToLoadRanking': 'Failed to load ranking',
    'cc.failedToParse': 'Failed to parse',
    'cc.errorProcessing': 'Error processing',
    'cc.loadCVsFromDB': 'Load CVs from Database',
    'cc.selectCandidatesToAdd': 'Select candidates to add to your ranking',
    'cc.searchByNameSkills': 'Search by name, skills...',
    'cc.deselectAll': 'Deselect All',
    'cc.selectAll': 'Select All',
    'cc.cvsFound': 'CVs found',
    'cc.selected': 'selected',
    'cc.loadSelected': 'Load Selected',
    'cc.noCVsInDB': 'No CVs found in database',
    'cc.score': 'Score',
    'cc.matchScore': 'Match Score',
    'cc.topCandidates': 'Top Candidates',
    'cc.skillsAnalysis': 'Skills Analysis',
    'cc.experience': 'Experience',
    'cc.projects': 'Projects',
    'cc.more': 'more',
    'cc.seniorBackendEngineer': 'e.g. Senior Backend Engineer',
    'cc.pythonDockerKubernetes': 'e.g. Python, Docker, Kubernetes, AWS, Microservices',
    
    // Jobs
    'jobs.title': 'Job Postings',
    'jobs.subtitle': 'Manage your open positions',
    'jobs.createNew': 'Create New Job',
    'jobs.noJobs': 'No job postings yet',
    'jobs.findCandidates': 'Find Candidates',
    'jobs.edit': 'Edit',
    'jobs.delete': 'Delete',
    'jobs.view': 'View',
    'jobs.candidates': 'candidates',
    'jobs.matched': 'matched',
    'jobs.createJob': 'Create Job',
    'jobs.createFirstJob': 'Create Your First Job',
    'jobs.noJobsDesc': 'Create your first job posting to start attracting candidates',
    'jobs.active': 'Active',
    'jobs.createNewJobPosting': 'Create New Job Posting',
    'jobs.aiExtractInfo': 'Our AI will automatically extract skills and requirements',
    'jobs.jobTitle': 'Job Title',
    'jobs.jobTitleRequired': 'Job Title *',
    'jobs.jobTitlePlaceholder': 'e.g., Senior Backend Developer with Python and AWS',
    'jobs.jobDescription': 'Job Description',
    'jobs.jobDescriptionPlaceholder': 'Describe the role, responsibilities, requirements, benefits, salary range, etc. Our AI will extract all relevant information...',
    'jobs.previewAIExtraction': '✨ Preview AI Extraction',
    'jobs.analyzingWithAI': 'Analyzing with AI...',
    'jobs.aiExtractedInformation': 'AI Extracted Information',
    'jobs.skills': 'Skills:',
    'jobs.experience': 'Experience:',
    'jobs.type': 'Type:',
    'jobs.location': 'Location:',
    'jobs.salary': 'Salary:',
    'jobs.seniority': 'Seniority:',
    'jobs.education': 'Education:',
    'jobs.creating': 'Creating...',
    'jobs.createJobPosting': 'Create Job Posting',
    'jobs.deleteConfirm': 'Are you sure you want to delete this job posting?',
    
    // CV Vault
    'cvs.title': 'CV Vault',
    'cvs.subtitle': 'View and manage all parsed CVs stored in database',
    'cvs.search': 'Search by candidate name...',
    'cvs.searchPlaceholder': 'Search by candidate name...',
    'cvs.noCVs': 'No CVs found',
    'cvs.noCVsDesc': 'Upload and parse CVs to see them here',
    'cvs.noCVsSearch': 'Try a different search term',
    'cvs.download': 'Download',
    'cvs.delete': 'Delete',
    'cvs.viewProfile': 'View Profile',
    'cvs.skills': 'Skills',
    'cvs.experience': 'Experience',
    'cvs.projects': 'Projects',
    'cvs.refresh': 'Refresh',
    'cvs.found': 'found',
    'cvs.parsed': 'Parsed',
    'cvs.uploadCVs': 'Upload CVs',
    'cvs.deleteConfirm': 'Are you sure you want to delete',
    'cvs.candidateCV': 'CV?',
    'cvs.addToFavorites': 'Add to favorites',
    'cvs.removeFromFavorites': 'Remove from favorites',
    'cvs.showFavoritesOnly': 'Show favorites only',
    'cvs.showAllCVs': 'Show all CVs',
    'cvs.noFavorites': 'No favorites yet',
    'cvs.noFavoritesDesc': 'Click the star icon on any CV to add it to your favorites',
    'cvs.favorites': 'Favorites',
    
    // AI Recruiter
    'recruiter.title': 'AI Recruiter',
    'recruiter.subtitle': 'Your intelligent recruitment assistant',
    'recruiter.placeholder': 'Ask me anything about candidates...',
    'recruiter.send': 'Send',
    'recruiter.thinking': 'Thinking',
    'recruiter.welcome': 'Hello! I\'m your AI recruitment assistant. Ask me about candidates, skills, or job matching.',
    'recruiter.welcomeTitle': '👋 Welcome to AI Recruiter',
    'recruiter.welcomeDesc': 'I\'m your intelligent recruitment assistant helping you find the perfect candidates.',
    'recruiter.whatICanHelp': 'What I can help you with:',
    'recruiter.searchCandidates': '🔍 **Search Candidates** — Find developers by skills, experience, or projects',
    'recruiter.analyzeMatches': '📊 **Analyze Matches** — Get detailed similarity scores and skill breakdowns',
    'recruiter.smartFilters': '🎯 **Smart Filters** — "Top 5 Java developers" or "Python experts with 3+ years"',
    'recruiter.naturalLanguage': '💡 **Natural Language** — Just describe what you\'re looking for',
    'recruiter.candidatesLoaded': 'candidates loaded and ready to search.',
    'recruiter.noCandidatesLoaded': '**No candidates loaded** — Upload CVs first to enable intelligent search.',
    'recruiter.tryAsking': '**Try asking:** "Find me the best React developers" or "Who has machine learning experience?"',
    'recruiter.newConversationStarted': '🚀 New Conversation Started',
    'recruiter.readyToHelp': 'Ready to help you find the perfect candidates!',
    'recruiter.candidatesAvailable': 'candidates available for search.',
    'recruiter.uploadCVsToEnable': '⚠️ Upload CVs to enable candidate search.',
    'recruiter.whatAreYouLookingFor': 'What are you looking for today?',
    'recruiter.newChat': 'New Chat',
    'recruiter.newConversation': 'New Conversation',
    'recruiter.candidates': 'Candidates',
    'recruiter.readyToSearch': 'Ready to search',
    'recruiter.aiRecruiter': 'AI Recruiter',
    'recruiter.you': 'You',
    'recruiter.analyzing': 'Analyzing...',
    'recruiter.askMeToFind': 'Ask me to find candidates...',
    'recruiter.stop': 'Stop',
    'recruiter.usesAdvancedMatching': 'AI Recruiter uses advanced matching algorithms to find the best candidates',
    'recruiter.connectionError': '## ❌ Connection Error',
    'recruiter.unableToReach': 'Unable to reach the AI service. Please check your connection and try again.',
    'recruiter.error': 'Error:',
    'recruiter.findJavaDevelopers': 'Find Java developers with Spring experience',
    'recruiter.showTop5': 'Show me the top 5 candidates',
    'recruiter.whoHasReact': 'Who has React and TypeScript skills?',
    'recruiter.findCandidatesWithExperience': 'Find candidates with 3+ years experience',
    'recruiter.startRecording': 'Start voice recording',
    'recruiter.stopRecording': 'Stop recording',
    'recruiter.recording': 'Recording...',
    'recruiter.listening': 'Listening...',
    'recruiter.noSpeechRecognition': 'Speech recognition is not supported in your browser',
    'recruiter.microphonePermission': 'Microphone permission is required for voice input',
    
    // History
    'history.title': 'Ranking History',
    'history.subtitle': 'View all past rankings',
    'history.noHistory': 'No ranking history yet',
    'history.load': 'Load',
    'history.delete': 'Delete',
    'history.candidates': 'candidates',
    'history.viewPastSessions': 'View your past CV ranking sessions and results',
    'history.startRankingCVs': 'Start Ranking CVs',
    'history.startRankingDesc': 'Start ranking CVs to build your history',
    'history.deleteConfirm': 'Delete this ranking history entry?',
    'history.topCandidates': 'Top Candidates',
    'history.scoringWeightsUsed': 'Scoring Weights Used',
    'history.viewOriginalJobPosting': 'View Original Job Posting',
    'history.best': 'Best:',
    'history.candidatesCount': 'candidates',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.actions': 'Actions',
    'common.noData': 'No data available',
    'common.back': 'Back',
    'common.refresh': 'Refresh',
    'common.loadingCVs': 'Loading CVs...',
    'common.failedToFetch': 'Failed to fetch CVs',
    'common.failedToDelete': 'Failed to delete CV',
    'common.unknownCandidate': 'Unknown Candidate',
    'common.notFound': 'not found',
    'common.posted': 'Posted',
    'common.location': 'Location',
    'common.type': 'Type',
    'common.salary': 'Salary',
    'common.experience': 'Experience',
    'common.seniority': 'Seniority',
    'common.education': 'Education',
    'common.requiredSkills': 'Required Skills',
    'common.jobDescription': 'Job Description',
    'common.responsibilities': 'Responsibilities',
    'common.requirements': 'Requirements',
    'common.benefits': 'Benefits',
    'common.findCandidatesForJob': 'Find Candidates for This Job',
    
    // Candidate Profile
    'profile.title': 'Profile',
    'profile.loading': 'Loading candidate profile...',
    'profile.notFound': 'Profile Not Found',
    'profile.notFoundDesc': 'The requested candidate profile could not be found.',
    'profile.backToVault': 'Back to CV Vault',
    'profile.exportJSON': 'Export JSON',
    'profile.professionalExperience': 'Professional Experience',
    'profile.projects': 'Projects',
    'profile.skillsExpertise': 'Skills & Expertise',
    'profile.education': 'Education',
    'profile.languages': 'Languages',
    'profile.certifications': 'Certifications',
    'profile.interests': 'Interests',
    'profile.parsedOn': 'Parsed on',
    'profile.experiences': 'Experiences',
    'profile.position': 'Position',
    'profile.company': 'Company',
    'profile.programmingLanguages': 'Programming Languages',
    'profile.frameworks': 'Frameworks',
    'profile.webTechnologies': 'Web Technologies',
    'profile.mobileTechnologies': 'Mobile Technologies',
    'profile.databases': 'Databases',
    'profile.devopsTools': 'DevOps & Tools',
    'profile.dataScience': 'Data Science',
    'profile.modelingDesign': 'Modeling & Design',
    'profile.softSkills': 'Soft Skills',
    'profile.otherSkills': 'Other Skills',
    'profile.degree': 'Degree',
    'profile.institution': 'Institution',
    'profile.location': 'Location',
    'profile.period': 'Period',
    'profile.more': 'more',
    
    // Methodology
    'methodology.title': 'Methodology',
    'methodology.subtitle': 'Our scoring system explained',
    'methodology.scoringMethodology': 'Scoring Methodology',
    'methodology.fineTune': 'Fine-tune how candidates are evaluated and ranked',
    'methodology.weightTotal': 'weight total',
    'methodology.reset': 'Reset',
    'methodology.saveChanges': 'Save Changes',
    'methodology.saved': 'Saved!',
    'methodology.categoryWeights': 'Category Weights',
    'methodology.distributePoints': 'Distribute 100 points across evaluation categories',
    'methodology.experience': 'Experience',
    'methodology.technicalSkills': 'Technical Skills',
    'methodology.projects': 'Projects',
    'methodology.education': 'Education',
    'methodology.signal': 'Signal',
    'methodology.experienceScoring': 'Experience Scoring',
    'methodology.companyTiersRecency': 'Company tiers, duration, and recency bonuses',
    'methodology.companyTierMultipliers': 'Company Tier Multipliers',
    'methodology.higherMultiplier': 'Higher multiplier = more points for experience at that company type',
    'methodology.durationScoring': 'Duration Scoring',
    'methodology.months': 'Months',
    'methodology.points': 'Points',
    'methodology.recencyBonusPenalty': 'Recency Bonus/Penalty',
    'methodology.currentPosition': 'Current Position',
    'methodology.within1Year': 'Within 1 Year',
    'methodology.within2Years': 'Within 2 Years',
    'methodology.yearsAgo': '5+ Years Ago',
    'methodology.roleRelevanceMaxPoints': 'Role Relevance Max Points',
    'methodology.multipleExperienceBonus': 'Multiple Experience Bonus',
    'methodology.technicalSkillsScoring': 'Technical Skills Scoring',
    'methodology.requiredSkillMatching': 'Required skill matching and depth',
    'methodology.matchingRequiredSkillsPoints': 'Matching Required Skills Points',
    'methodology.depthBonusPoints': 'Depth Bonus Points',
    'methodology.minSkillsForDepthBonus': 'Min Skills for Depth Bonus',
    'methodology.projectsScoring': 'Projects Scoring',
    'methodology.basePointsRelevance': 'Base points and relevance bonuses',
    'methodology.basePointsPerProject': 'Base Points per Project',
    'methodology.maxProjectsCounted': 'Max Projects Counted',
    'methodology.relevanceBonus': 'Relevance Bonus',
    'methodology.noMatchPenalty': 'No Match Penalty',
    'methodology.educationScoring': 'Education Scoring',
    'methodology.degreeLevelsCertifications': 'Degree levels and certifications',
    'methodology.phdPoints': 'PhD Points',
    'methodology.masterPoints': 'Master Points',
    'methodology.bachelorPoints': 'Bachelor Points',
    'methodology.maxEducationScore': 'Max Education Score',
    'methodology.certificationBonus': 'Certification Bonus',
    'methodology.signalConsistencyScoring': 'Signal/Consistency Scoring',
    'methodology.overallProfileQuality': 'Overall profile quality signals',
    'methodology.maxScore': 'Max Score',
    'methodology.howToUse': 'How to use:',
    'methodology.adjustParameter': 'Adjust any parameter to customize the scoring methodology',
    'methodology.weightsMustTotal': 'Category weights must total exactly 100 points',
    'methodology.changesSaved': 'Changes are saved to localStorage and will apply to all future rankings',
    'methodology.resetToDefault': 'Click "Reset to Default" to restore original values',
    'methodology.rankingAPIUses': 'The ranking API will automatically use your custom configuration',
    
    // About
    'about.title': 'About',
    'about.subtitle': 'Learn more about Smart Hire',
    'about.aboutCVRanking': 'About CV Ranking System',
    'about.sophisticatedPlatform': 'A sophisticated, explainable candidate ranking platform designed specifically for',
    'about.informatique': 'INFORMATIQUE',
    'about.positions': 'positions.',
    'about.ourMission': 'Our Mission',
    'about.missionText1': 'We believe that candidate ranking should be transparent, fair, and based on structured, explainable criteria rather than opaque AI decisions. Our system uses a multi-dimensional scoring model inspired by real recruiter decision processes in the IT industry.',
    'about.missionText2': 'Every candidate receives a comprehensive score across five key dimensions, with detailed explanations for each component. This ensures that hiring decisions are not just fast, but also understandable and defensible.',
    'about.keyFeatures': 'Key Features',
    'about.whatMakesUnique': 'What makes our ranking system unique',
    'about.structuredScoring': 'Structured Scoring',
    'about.structuredScoringDesc': 'Multi-dimensional evaluation system based on experience, skills, projects, education, and consistency.',
    'about.explainableResults': 'Explainable Results',
    'about.explainableResultsDesc': 'Every ranking comes with detailed explanations, not just a score. Understand why candidates are ranked the way they are.',
    'about.fastProcessing': 'Fast Processing',
    'about.fastProcessingDesc': 'Quickly parse and rank multiple CVs simultaneously with our optimized processing pipeline.',
    'about.recruiterInspired': 'Recruiter-Inspired',
    'about.recruiterInspiredDesc': 'Scoring model designed based on real recruiter decision-making processes in the IT field.',
    'about.technicalFocus': 'Technical Focus',
    'about.technicalFocusDesc': 'Specialized for INFORMATIQUE (IT/Computer Science) positions with deep understanding of technical requirements.',
    'about.qualityAssurance': 'Quality Assurance',
    'about.qualityAssuranceDesc': 'Comprehensive evaluation ensuring the best candidates rise to the top through rigorous scoring.',
    'about.scoringMethodology': 'Scoring Methodology',
    'about.experienceQuality': 'Experience Quality',
    'about.experienceQualityWeight': '35%',
    'about.experienceQualityDesc': 'Evaluates years of experience, role relevance, and career progression',
    'about.technicalSkills': 'Technical Skills',
    'about.technicalSkillsWeight': '25%',
    'about.technicalSkillsDesc': 'Assesses proficiency in required technologies and tools',
    'about.projectsImpact': 'Projects & Impact',
    'about.projectsImpactWeight': '20%',
    'about.projectsImpactDesc': 'Measures project complexity, scale, and business impact',
    'about.educationCertifications': 'Education & Certifications',
    'about.educationCertificationsWeight': '10%',
    'about.educationCertificationsDesc': 'Considers academic background and professional certifications',
    'about.signalConsistency': 'Signal & Consistency',
    'about.signalConsistencyWeight': '10%',
    'about.signalConsistencyDesc': 'Analyzes resume quality, consistency, and professional signals',
    'about.howItWorks': 'How It Works',
    'about.uploadCVs': 'Upload CVs',
    'about.uploadCVsDesc': 'Upload candidate CVs in multiple formats (PDF, images, or JSON). Our system automatically parses and extracts relevant information.',
    'about.defineRequirements': 'Define Requirements',
    'about.defineRequirementsDesc': 'Specify the job role, required skills, and field. This helps our system tailor the scoring to match your specific needs.',
    'about.getRankings': 'Get Rankings',
    'about.getRankingsDesc': 'Receive ranked candidates with detailed scores, explanations, and breakdowns across all evaluation dimensions.',
  },
  fr: {
    // Navbar
    'nav.commandCenter': 'Centre de Commande',
    'nav.jobs': 'Emplois',
    'nav.cvVault': 'Coffre CV',
    'nav.aiRecruiter': 'Recruteur IA',
    'nav.history': 'Historique',
    'nav.methodology': 'Méthodologie',
    'nav.about': 'À propos',
    'nav.ollamaLive': 'OLLAMA EN LIGNE',
    'nav.smartHire': 'Smart Hire',
    
    // Landing Page
    'landing.badge': 'Smart Hire',
    'landing.heroTitle1': 'Le Futur du',
    'landing.heroTitle2': 'Recrutement Intelligent',
    'landing.heroSubtitle': 'Transformez votre processus de recrutement avec l\'analyse de CV par IA, le classement intelligent des candidats et des insights en temps réel',
    'landing.getStarted': 'Commencer',
    'landing.learnMore': 'En Savoir Plus',
    'landing.howItWorks': 'Comment Ça Marche',
    'landing.howItWorksSubtitle': 'Trois étapes simples pour révolutionner votre processus de recrutement',
    'landing.step1Title': 'Télécharger les CV',
    'landing.step1Desc': 'Téléchargez les CV des candidats ou sélectionnez depuis votre base de données. Notre IA traite et extrait instantanément les informations clés.',
    'landing.step2Title': 'Analyse IA',
    'landing.step2Desc': 'Des algorithmes avancés analysent les compétences, l\'expérience, les projets et la formation pour créer des profils complets.',
    'landing.step3Title': 'Obtenez les Classements',
    'landing.step3Desc': 'Recevez des classements intelligents avec des explications détaillées pour prendre des décisions éclairées.',
    'landing.powerfulFeatures': 'Fonctionnalités Puissantes',
    'landing.featuresSubtitle': 'Tout ce dont vous avez besoin pour un recrutement intelligent',
    'landing.feature1': 'Parsing Intelligent',
    'landing.feature1Desc': 'Extraire les données clés de tout format de CV',
    'landing.feature2': 'Matching Précis',
    'landing.feature2Desc': 'Faire correspondre les candidats aux exigences',
    'landing.feature3': 'Évaluation des Compétences',
    'landing.feature3Desc': 'Évaluer les compétences techniques et personnelles',
    'landing.feature4': 'Collaboration d\'Équipe',
    'landing.feature4Desc': 'Partagez les insights avec votre équipe',
    'landing.feature5': 'Sécurisé & Privé',
    'landing.feature5Desc': 'Protection des données de niveau entreprise',
    'landing.feature6': 'Ultra Rapide',
    'landing.feature6Desc': 'Traitez des milliers de CV instantanément',
    'landing.ctaTitle': 'Prêt à Transformer Votre Recrutement?',
    'landing.ctaSubtitle': 'Rejoignez des milliers de recruteurs qui ont déjà révolutionné leur processus d\'embauche',
    'landing.startNow': 'Commencer Maintenant',
    'landing.footer': 'Capgemini Smart Hire. Propulsé par l\'IA.',
    
    // Command Center
    'cc.title': 'Centre de Commande',
    'cc.subtitle': 'Classement de CV et analyse des candidats par IA',
    'cc.targetRole': 'Poste Cible',
    'cc.targetRolePlaceholder': 'ex., Développeur Full Stack',
    'cc.requiredSkills': 'Compétences Requises',
    'cc.requiredSkillsPlaceholder': 'ex., React, Node.js, Python',
    'cc.uploadCVs': 'Télécharger les CV',
    'cc.dragDrop': 'Glissez-déposez les fichiers ici ou cliquez pour parcourir',
    'cc.supportedFormats': 'Formats supportés: PDF, DOC, DOCX',
    'cc.loadFromDB': 'Charger depuis la Base',
    'cc.candidates': 'Candidats',
    'cc.noCandidates': 'Aucun candidat chargé',
    'cc.rankCandidates': 'Classer les Candidats',
    'cc.ranking': 'Classement',
    'cc.results': 'Résultats',
    'cc.noResults': 'Pas encore de résultats',
    'cc.parsing': 'Analyse en cours',
    'cc.checkWithAI': 'Vérifier avec l\'IA',
    'cc.saveRanking': 'Sauvegarder le Classement',
    'cc.subtitleDesc': 'Gérer les opérations de numérisation, classement et analyse.',
    'cc.scanningDocuments': 'NUMÉRISATION DES DOCUMENTS',
    'cc.calculatingRankings': 'CALCUL DES CLASSEMENTS',
    'cc.uploadResumes': 'Télécharger les CV',
    'cc.scanningDocumentsText': 'Numérisation des Documents',
    'cc.pleaseWait': 'Veuillez patienter pendant le traitement de vos fichiers',
    'cc.dragDropFiles': 'Glissez-déposez les fichiers PDF, DOCX ou JSON',
    'cc.processing': 'Traitement...',
    'cc.selectFiles': 'Sélectionner les Fichiers',
    'cc.loadFromDatabase': 'Charger depuis la Base de Données',
    'cc.selectCVsFromDB': 'Sélectionnez les CV de votre base de données',
    'cc.candidatesCount': 'Candidats',
    'cc.calculateRanking': 'Calculer le Classement',
    'cc.calculating': 'Calcul',
    'cc.roles': 'rôles',
    'cc.languages': 'langages',
    'cc.saveToDatabase': 'Enregistrer dans la base de données',
    'cc.removeCandidate': 'Supprimer le candidat',
    'cc.rankingResults': 'Résultats du Classement',
    'cc.readyToRank': 'Prêt à Classer',
    'cc.readyToRankDesc': 'Téléchargez les CV des candidats et définissez les exigences du poste pour générer des classements alimentés par l\'IA.',
    'cc.uploadCVsFirst': 'Téléchargez d\'abord les CV',
    'cc.failedToLoadRanking': 'Échec du chargement du classement',
    'cc.failedToParse': 'Échec de l\'analyse',
    'cc.errorProcessing': 'Erreur de traitement',
    'cc.loadCVsFromDB': 'Charger les CV depuis la Base',
    'cc.selectCandidatesToAdd': 'Sélectionnez les candidats à ajouter à votre classement',
    'cc.searchByNameSkills': 'Rechercher par nom, compétences...',
    'cc.deselectAll': 'Tout Désélectionner',
    'cc.selectAll': 'Tout Sélectionner',
    'cc.cvsFound': 'CV trouvés',
    'cc.selected': 'sélectionné',
    'cc.loadSelected': 'Charger les Sélectionnés',
    'cc.noCVsInDB': 'Aucun CV trouvé dans la base de données',
    'cc.score': 'Score',
    'cc.matchScore': 'Score de Correspondance',
    'cc.topCandidates': 'Meilleurs Candidats',
    'cc.skillsAnalysis': 'Analyse des Compétences',
    'cc.experience': 'Expérience',
    'cc.projects': 'Projets',
    'cc.more': 'de plus',
    'cc.seniorBackendEngineer': 'ex. Développeur Backend Senior',
    'cc.pythonDockerKubernetes': 'ex. Python, Docker, Kubernetes, AWS, Microservices',
    
    // Jobs
    'jobs.title': 'Offres d\'Emploi',
    'jobs.subtitle': 'Gérez vos postes ouverts',
    'jobs.createNew': 'Créer une Offre',
    'jobs.noJobs': 'Aucune offre d\'emploi',
    'jobs.findCandidates': 'Trouver des Candidats',
    'jobs.edit': 'Modifier',
    'jobs.delete': 'Supprimer',
    'jobs.view': 'Voir',
    'jobs.candidates': 'candidats',
    'jobs.matched': 'correspondants',
    'jobs.createJob': 'Créer un Emploi',
    'jobs.createFirstJob': 'Créer Votre Premier Emploi',
    'jobs.noJobsDesc': 'Créez votre première offre d\'emploi pour commencer à attirer des candidats',
    'jobs.active': 'Actif',
    'jobs.createNewJobPosting': 'Créer une Nouvelle Offre d\'Emploi',
    'jobs.aiExtractInfo': 'Notre IA extraira automatiquement les compétences et les exigences',
    'jobs.jobTitle': 'Titre du Poste',
    'jobs.jobTitleRequired': 'Titre du Poste *',
    'jobs.jobTitlePlaceholder': 'ex., Développeur Backend Senior avec Python et AWS',
    'jobs.jobDescription': 'Description du Poste',
    'jobs.jobDescriptionPlaceholder': 'Décrivez le rôle, les responsabilités, les exigences, les avantages, la fourchette salariale, etc. Notre IA extraira toutes les informations pertinentes...',
    'jobs.previewAIExtraction': '✨ Aperçu de l\'Extraction IA',
    'jobs.analyzingWithAI': 'Analyse avec l\'IA...',
    'jobs.aiExtractedInformation': 'Informations Extraites par l\'IA',
    'jobs.skills': 'Compétences:',
    'jobs.experience': 'Expérience:',
    'jobs.type': 'Type:',
    'jobs.location': 'Localisation:',
    'jobs.salary': 'Salaire:',
    'jobs.seniority': 'Séniorité:',
    'jobs.education': 'Formation:',
    'jobs.creating': 'Création...',
    'jobs.createJobPosting': 'Créer l\'Offre d\'Emploi',
    'jobs.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cette offre d\'emploi?',
    
    // CV Vault
    'cvs.title': 'Coffre CV',
    'cvs.subtitle': 'Voir et gérer tous les CV analysés stockés dans la base de données',
    'cvs.search': 'Rechercher par nom de candidat...',
    'cvs.searchPlaceholder': 'Rechercher par nom de candidat...',
    'cvs.noCVs': 'Aucun CV trouvé',
    'cvs.noCVsDesc': 'Téléchargez et analysez des CV pour les voir ici',
    'cvs.noCVsSearch': 'Essayez un autre terme de recherche',
    'cvs.download': 'Télécharger',
    'cvs.delete': 'Supprimer',
    'cvs.viewProfile': 'Voir le Profil',
    'cvs.skills': 'Compétences',
    'cvs.experience': 'Expérience',
    'cvs.projects': 'Projets',
    'cvs.refresh': 'Actualiser',
    'cvs.found': 'trouvé',
    'cvs.parsed': 'Analysé',
    'cvs.uploadCVs': 'Télécharger les CV',
    'cvs.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer',
    'cvs.candidateCV': 'CV?',
    'cvs.addToFavorites': 'Ajouter aux favoris',
    'cvs.removeFromFavorites': 'Retirer des favoris',
    'cvs.showFavoritesOnly': 'Afficher uniquement les favoris',
    'cvs.showAllCVs': 'Afficher tous les CV',
    'cvs.noFavorites': 'Aucun favori pour le moment',
    'cvs.noFavoritesDesc': 'Cliquez sur l\'icône étoile sur n\'importe quel CV pour l\'ajouter à vos favoris',
    'cvs.favorites': 'Favoris',
    
    // AI Recruiter
    'recruiter.title': 'Recruteur IA',
    'recruiter.subtitle': 'Votre assistant de recrutement intelligent',
    'recruiter.placeholder': 'Posez-moi une question sur les candidats...',
    'recruiter.send': 'Envoyer',
    'recruiter.thinking': 'Réflexion',
    'recruiter.welcome': 'Bonjour! Je suis votre assistant de recrutement IA. Posez-moi des questions sur les candidats, les compétences ou le matching.',
    'recruiter.welcomeTitle': '👋 Bienvenue dans le Recruteur IA',
    'recruiter.welcomeDesc': 'Je suis votre assistant de recrutement intelligent qui vous aide à trouver les candidats parfaits.',
    'recruiter.whatICanHelp': 'Ce avec quoi je peux vous aider:',
    'recruiter.searchCandidates': '🔍 **Rechercher des Candidats** — Trouvez des développeurs par compétences, expérience ou projets',
    'recruiter.analyzeMatches': '📊 **Analyser les Correspondances** — Obtenez des scores de similarité détaillés et des analyses de compétences',
    'recruiter.smartFilters': '🎯 **Filtres Intelligents** — "Top 5 développeurs Java" ou "Experts Python avec 3+ ans"',
    'recruiter.naturalLanguage': '💡 **Langage Naturel** — Décrivez simplement ce que vous recherchez',
    'recruiter.candidatesLoaded': 'candidats chargés et prêts à rechercher.',
    'recruiter.noCandidatesLoaded': '**Aucun candidat chargé** — Téléchargez d\'abord les CV pour activer la recherche intelligente.',
    'recruiter.tryAsking': '**Essayez de demander:** "Trouvez-moi les meilleurs développeurs React" ou "Qui a de l\'expérience en machine learning?"',
    'recruiter.newConversationStarted': '🚀 Nouvelle Conversation Démarrée',
    'recruiter.readyToHelp': 'Prêt à vous aider à trouver les candidats parfaits!',
    'recruiter.candidatesAvailable': 'candidats disponibles pour la recherche.',
    'recruiter.uploadCVsToEnable': '⚠️ Téléchargez les CV pour activer la recherche de candidats.',
    'recruiter.whatAreYouLookingFor': 'Que recherchez-vous aujourd\'hui?',
    'recruiter.newChat': 'Nouveau Chat',
    'recruiter.newConversation': 'Nouvelle Conversation',
    'recruiter.candidates': 'Candidats',
    'recruiter.readyToSearch': 'Prêt à rechercher',
    'recruiter.aiRecruiter': 'Recruteur IA',
    'recruiter.you': 'Vous',
    'recruiter.analyzing': 'Analyse...',
    'recruiter.askMeToFind': 'Demandez-moi de trouver des candidats...',
    'recruiter.stop': 'Arrêter',
    'recruiter.usesAdvancedMatching': 'Le Recruteur IA utilise des algorithmes de correspondance avancés pour trouver les meilleurs candidats',
    'recruiter.connectionError': '## ❌ Erreur de Connexion',
    'recruiter.unableToReach': 'Impossible d\'atteindre le service IA. Veuillez vérifier votre connexion et réessayer.',
    'recruiter.error': 'Erreur:',
    'recruiter.findJavaDevelopers': 'Trouvez des développeurs Java avec expérience Spring',
    'recruiter.showTop5': 'Montrez-moi les 5 meilleurs candidats',
    'recruiter.whoHasReact': 'Qui a des compétences React et TypeScript?',
    'recruiter.findCandidatesWithExperience': 'Trouvez des candidats avec 3+ ans d\'expérience',
    'recruiter.startRecording': 'Démarrer l\'enregistrement vocal',
    'recruiter.stopRecording': 'Arrêter l\'enregistrement',
    'recruiter.recording': 'Enregistrement...',
    'recruiter.listening': 'Écoute...',
    'recruiter.noSpeechRecognition': 'La reconnaissance vocale n\'est pas prise en charge dans votre navigateur',
    'recruiter.microphonePermission': 'L\'autorisation du microphone est requise pour la saisie vocale',
    
    // History
    'history.title': 'Historique des Classements',
    'history.subtitle': 'Voir tous les classements passés',
    'history.noHistory': 'Aucun historique de classement',
    'history.load': 'Charger',
    'history.delete': 'Supprimer',
    'history.candidates': 'candidats',
    'history.viewPastSessions': 'Voir vos sessions de classement de CV passées et résultats',
    'history.startRankingCVs': 'Commencer le Classement des CV',
    'history.startRankingDesc': 'Commencez à classer les CV pour créer votre historique',
    'history.deleteConfirm': 'Supprimer cette entrée d\'historique de classement?',
    'history.topCandidates': 'Meilleurs Candidats',
    'history.scoringWeightsUsed': 'Pondérations de Score Utilisées',
    'history.viewOriginalJobPosting': 'Voir l\'Offre d\'Emploi Originale',
    'history.best': 'Meilleur:',
    'history.candidatesCount': 'candidats',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Sauvegarder',
    'common.close': 'Fermer',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.actions': 'Actions',
    'common.noData': 'Aucune donnée disponible',
    'common.back': 'Retour',
    'common.refresh': 'Actualiser',
    'common.loadingCVs': 'Chargement des CV...',
    'common.failedToFetch': 'Échec du chargement des CV',
    'common.failedToDelete': 'Échec de la suppression du CV',
    'common.unknownCandidate': 'Candidat Inconnu',
    'common.notFound': 'non trouvé',
    'common.posted': 'Publié',
    'common.location': 'Localisation',
    'common.type': 'Type',
    'common.salary': 'Salaire',
    'common.experience': 'Expérience',
    'common.seniority': 'Séniorité',
    'common.education': 'Formation',
    'common.requiredSkills': 'Compétences Requises',
    'common.jobDescription': 'Description du Poste',
    'common.responsibilities': 'Responsabilités',
    'common.requirements': 'Exigences',
    'common.benefits': 'Avantages',
    'common.findCandidatesForJob': 'Trouver des Candidats pour ce Poste',
    
    // Candidate Profile
    'profile.title': 'Profil',
    'profile.loading': 'Chargement du profil du candidat...',
    'profile.notFound': 'Profil Non Trouvé',
    'profile.notFoundDesc': 'Le profil du candidat demandé n\'a pas pu être trouvé.',
    'profile.backToVault': 'Retour au Coffre CV',
    'profile.exportJSON': 'Exporter JSON',
    'profile.professionalExperience': 'Expérience Professionnelle',
    'profile.projects': 'Projets',
    'profile.skillsExpertise': 'Compétences et Expertise',
    'profile.education': 'Formation',
    'profile.languages': 'Langues',
    'profile.certifications': 'Certifications',
    'profile.interests': 'Centres d\'Intérêt',
    'profile.parsedOn': 'Analysé le',
    'profile.experiences': 'Expériences',
    'profile.position': 'Poste',
    'profile.company': 'Entreprise',
    'profile.programmingLanguages': 'Langages de Programmation',
    'profile.frameworks': 'Frameworks',
    'profile.webTechnologies': 'Technologies Web',
    'profile.mobileTechnologies': 'Technologies Mobiles',
    'profile.databases': 'Bases de Données',
    'profile.devopsTools': 'DevOps et Outils',
    'profile.dataScience': 'Science des Données',
    'profile.modelingDesign': 'Modélisation et Conception',
    'profile.softSkills': 'Compétences Personnelles',
    'profile.otherSkills': 'Autres Compétences',
    'profile.degree': 'Diplôme',
    'profile.institution': 'Établissement',
    'profile.location': 'Localisation',
    'profile.period': 'Période',
    'profile.more': 'de plus',
    
    // Methodology
    'methodology.title': 'Méthodologie',
    'methodology.subtitle': 'Notre système de notation expliqué',
    'methodology.scoringMethodology': 'Méthodologie de Notation',
    'methodology.fineTune': 'Ajustez la façon dont les candidats sont évalués et classés',
    'methodology.weightTotal': 'total de poids',
    'methodology.reset': 'Réinitialiser',
    'methodology.saveChanges': 'Enregistrer les Modifications',
    'methodology.saved': 'Enregistré!',
    'methodology.categoryWeights': 'Pondérations des Catégories',
    'methodology.distributePoints': 'Répartissez 100 points entre les catégories d\'évaluation',
    'methodology.experience': 'Expérience',
    'methodology.technicalSkills': 'Compétences Techniques',
    'methodology.projects': 'Projets',
    'methodology.education': 'Formation',
    'methodology.signal': 'Signal',
    'methodology.experienceScoring': 'Notation de l\'Expérience',
    'methodology.companyTiersRecency': 'Niveaux d\'entreprise, durée et bonus de récence',
    'methodology.companyTierMultipliers': 'Multiplicateurs de Niveau d\'Entreprise',
    'methodology.higherMultiplier': 'Multiplicateur plus élevé = plus de points pour l\'expérience dans ce type d\'entreprise',
    'methodology.durationScoring': 'Notation de la Durée',
    'methodology.months': 'Mois',
    'methodology.points': 'Points',
    'methodology.recencyBonusPenalty': 'Bonus/Pénalité de Récence',
    'methodology.currentPosition': 'Poste Actuel',
    'methodology.within1Year': 'Dans 1 An',
    'methodology.within2Years': 'Dans 2 Ans',
    'methodology.yearsAgo': 'Il y a 5+ Ans',
    'methodology.roleRelevanceMaxPoints': 'Points Maximum de Pertinence du Rôle',
    'methodology.multipleExperienceBonus': 'Bonus d\'Expérience Multiple',
    'methodology.technicalSkillsScoring': 'Notation des Compétences Techniques',
    'methodology.requiredSkillMatching': 'Correspondance des compétences requises et profondeur',
    'methodology.matchingRequiredSkillsPoints': 'Points de Correspondance des Compétences Requises',
    'methodology.depthBonusPoints': 'Points de Bonus de Profondeur',
    'methodology.minSkillsForDepthBonus': 'Compétences Min pour Bonus de Profondeur',
    'methodology.projectsScoring': 'Notation des Projets',
    'methodology.basePointsRelevance': 'Points de base et bonus de pertinence',
    'methodology.basePointsPerProject': 'Points de Base par Projet',
    'methodology.maxProjectsCounted': 'Nombre Maximum de Projets Comptés',
    'methodology.relevanceBonus': 'Bonus de Pertinence',
    'methodology.noMatchPenalty': 'Pénalité d\'Aucune Correspondance',
    'methodology.educationScoring': 'Notation de la Formation',
    'methodology.degreeLevelsCertifications': 'Niveaux de diplôme et certifications',
    'methodology.phdPoints': 'Points Doctorat',
    'methodology.masterPoints': 'Points Master',
    'methodology.bachelorPoints': 'Points Licence',
    'methodology.maxEducationScore': 'Score Maximum de Formation',
    'methodology.certificationBonus': 'Bonus de Certification',
    'methodology.signalConsistencyScoring': 'Notation Signal/Cohérence',
    'methodology.overallProfileQuality': 'Signaux de qualité de profil global',
    'methodology.maxScore': 'Score Maximum',
    'methodology.howToUse': 'Comment utiliser:',
    'methodology.adjustParameter': 'Ajustez n\'importe quel paramètre pour personnaliser la méthodologie de notation',
    'methodology.weightsMustTotal': 'Les pondérations des catégories doivent totaliser exactement 100 points',
    'methodology.changesSaved': 'Les modifications sont enregistrées dans localStorage et s\'appliqueront à tous les classements futurs',
    'methodology.resetToDefault': 'Cliquez sur "Réinitialiser par Défaut" pour restaurer les valeurs d\'origine',
    'methodology.rankingAPIUses': 'L\'API de classement utilisera automatiquement votre configuration personnalisée',
    
    // About
    'about.title': 'À propos',
    'about.subtitle': 'En savoir plus sur Smart Hire',
    'about.aboutCVRanking': 'À propos du Système de Classement de CV',
    'about.sophisticatedPlatform': 'Une plateforme de classement de candidats sophistiquée et explicable conçue spécifiquement pour les postes',
    'about.informatique': 'INFORMATIQUE',
    'about.positions': '.',
    'about.ourMission': 'Notre Mission',
    'about.missionText1': 'Nous croyons que le classement des candidats devrait être transparent, équitable et basé sur des critères structurés et explicables plutôt que sur des décisions IA opaques. Notre système utilise un modèle de notation multidimensionnel inspiré des processus de décision réels des recruteurs dans l\'industrie informatique.',
    'about.missionText2': 'Chaque candidat reçoit un score complet sur cinq dimensions clés, avec des explications détaillées pour chaque composante. Cela garantit que les décisions d\'embauche ne sont pas seulement rapides, mais aussi compréhensibles et défendables.',
    'about.keyFeatures': 'Fonctionnalités Clés',
    'about.whatMakesUnique': 'Ce qui rend notre système de classement unique',
    'about.structuredScoring': 'Notation Structurée',
    'about.structuredScoringDesc': 'Système d\'évaluation multidimensionnel basé sur l\'expérience, les compétences, les projets, la formation et la cohérence.',
    'about.explainableResults': 'Résultats Explicables',
    'about.explainableResultsDesc': 'Chaque classement est accompagné d\'explications détaillées, pas seulement d\'un score. Comprenez pourquoi les candidats sont classés de cette façon.',
    'about.fastProcessing': 'Traitement Rapide',
    'about.fastProcessingDesc': 'Analysez et classez rapidement plusieurs CV simultanément avec notre pipeline de traitement optimisé.',
    'about.recruiterInspired': 'Inspiré des Recruteurs',
    'about.recruiterInspiredDesc': 'Modèle de notation conçu sur la base des processus réels de prise de décision des recruteurs dans le domaine informatique.',
    'about.technicalFocus': 'Focus Technique',
    'about.technicalFocusDesc': 'Spécialisé pour les postes INFORMATIQUE (IT/Informatique) avec une compréhension approfondie des exigences techniques.',
    'about.qualityAssurance': 'Assurance Qualité',
    'about.qualityAssuranceDesc': 'Évaluation complète garantissant que les meilleurs candidats remontent en haut grâce à un scoring rigoureux.',
    'about.scoringMethodology': 'Méthodologie de Notation',
    'about.experienceQuality': 'Qualité de l\'Expérience',
    'about.experienceQualityWeight': '35%',
    'about.experienceQualityDesc': 'Évalue les années d\'expérience, la pertinence du rôle et la progression de carrière',
    'about.technicalSkills': 'Compétences Techniques',
    'about.technicalSkillsWeight': '25%',
    'about.technicalSkillsDesc': 'Évalue la maîtrise des technologies et outils requis',
    'about.projectsImpact': 'Projets et Impact',
    'about.projectsImpactWeight': '20%',
    'about.projectsImpactDesc': 'Mesure la complexité, l\'envergure et l\'impact commercial des projets',
    'about.educationCertifications': 'Formation et Certifications',
    'about.educationCertificationsWeight': '10%',
    'about.educationCertificationsDesc': 'Prend en compte le parcours académique et les certifications professionnelles',
    'about.signalConsistency': 'Signal et Cohérence',
    'about.signalConsistencyWeight': '10%',
    'about.signalConsistencyDesc': 'Analyse la qualité du CV, la cohérence et les signaux professionnels',
    'about.howItWorks': 'Comment Ça Marche',
    'about.uploadCVs': 'Télécharger les CV',
    'about.uploadCVsDesc': 'Téléchargez les CV des candidats dans plusieurs formats (PDF, images ou JSON). Notre système analyse et extrait automatiquement les informations pertinentes.',
    'about.defineRequirements': 'Définir les Exigences',
    'about.defineRequirementsDesc': 'Spécifiez le rôle, les compétences requises et le domaine. Cela aide notre système à adapter le scoring à vos besoins spécifiques.',
    'about.getRankings': 'Obtenir les Classements',
    'about.getRankingsDesc': 'Recevez des candidats classés avec des scores détaillés, des explications et des répartitions sur toutes les dimensions d\'évaluation.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load saved language preference
    const saved = localStorage.getItem('language') as Language;
    if (saved && (saved === 'en' || saved === 'fr')) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
